package com.android.mb.evergreen.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.mb.evergreen.entity.Category;
import com.android.mb.evergreen.entity.Examine;
import com.android.mb.evergreen.entity.User;

import com.android.mb.evergreen.greendao.CategoryDao;
import com.android.mb.evergreen.greendao.ExamineDao;
import com.android.mb.evergreen.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig examineDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CategoryDao categoryDao;
    private final ExamineDao examineDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        examineDaoConfig = daoConfigMap.get(ExamineDao.class).clone();
        examineDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        examineDao = new ExamineDao(examineDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Examine.class, examineDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        categoryDaoConfig.clearIdentityScope();
        examineDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public ExamineDao getExamineDao() {
        return examineDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
