package com.android.mb.evergreen.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.android.mb.evergreen.entity.Examine;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXAMINE".
*/
public class ExamineDao extends AbstractDao<Examine, Long> {

    public static final String TABLENAME = "EXAMINE";

    /**
     * Properties of entity Examine.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property TestDate = new Property(2, String.class, "testDate", false, "TEST_DATE");
        public final static Property Serial = new Property(3, String.class, "serial", false, "SERIAL");
        public final static Property Num = new Property(4, String.class, "num", false, "NUM");
        public final static Property UserId = new Property(5, Long.class, "userId", false, "USER_ID");
        public final static Property UserName = new Property(6, String.class, "userName", false, "USER_NAME");
        public final static Property Result = new Property(7, String.class, "result", false, "RESULT");
        public final static Property Image = new Property(8, String.class, "image", false, "IMAGE");
        public final static Property Checked = new Property(9, boolean.class, "checked", false, "CHECKED");
    }


    public ExamineDao(DaoConfig config) {
        super(config);
    }
    
    public ExamineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXAMINE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"TEST_DATE\" TEXT," + // 2: testDate
                "\"SERIAL\" TEXT," + // 3: serial
                "\"NUM\" TEXT," + // 4: num
                "\"USER_ID\" INTEGER," + // 5: userId
                "\"USER_NAME\" TEXT," + // 6: userName
                "\"RESULT\" TEXT," + // 7: result
                "\"IMAGE\" TEXT," + // 8: image
                "\"CHECKED\" INTEGER NOT NULL );"); // 9: checked
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXAMINE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Examine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String testDate = entity.getTestDate();
        if (testDate != null) {
            stmt.bindString(3, testDate);
        }
 
        String serial = entity.getSerial();
        if (serial != null) {
            stmt.bindString(4, serial);
        }
 
        String num = entity.getNum();
        if (num != null) {
            stmt.bindString(5, num);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(6, userId);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(7, userName);
        }
 
        String result = entity.getResult();
        if (result != null) {
            stmt.bindString(8, result);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(9, image);
        }
        stmt.bindLong(10, entity.getChecked() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Examine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String testDate = entity.getTestDate();
        if (testDate != null) {
            stmt.bindString(3, testDate);
        }
 
        String serial = entity.getSerial();
        if (serial != null) {
            stmt.bindString(4, serial);
        }
 
        String num = entity.getNum();
        if (num != null) {
            stmt.bindString(5, num);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(6, userId);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(7, userName);
        }
 
        String result = entity.getResult();
        if (result != null) {
            stmt.bindString(8, result);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(9, image);
        }
        stmt.bindLong(10, entity.getChecked() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Examine readEntity(Cursor cursor, int offset) {
        Examine entity = new Examine( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // testDate
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // serial
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // num
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // userId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // userName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // result
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // image
            cursor.getShort(offset + 9) != 0 // checked
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Examine entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTestDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSerial(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNum(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setUserName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setResult(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setImage(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setChecked(cursor.getShort(offset + 9) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Examine entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Examine entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Examine entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
